### ISSUE TITLE
help me solve these error on my logd

### ISSUE THREAD

**Issue by iamvictorabedi** [Charca/bootbot#143]
i receive these error on my logs when ever i hit a button to that has a payload
TypeError: Cannot read property 'forEach' of undefined
    at data.entry.forEach (/home/victor/unganisha/lib/BootBot.js:649:23)
    at Array.forEach (<anonymous>)
    at BootBot.handleFacebookData (/home/victor/unganisha/lib/BootBot.js:647:16)
    at app.post (/home/victor/unganisha/lib/BootBot.js:634:12)
    at Layer.handle [as handle_request] (/home/victor/unganisha/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/victor/unganisha/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/victor/unganisha/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/victor/unganisha/node_modules/express/lib/router/layer.js:95:5)
    at /home/victor/unganisha/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/victor/unganisha/node_modules/express/lib/router/index.js:335:12)
TypeError: Cannot read property 'forEach' of undefined
    at data.entry.forEach (/home/victor/unganisha/lib/BootBot.js:649:23)
    at Array.forEach (<anonymous>)
    at BootBot.handleFacebookData (/home/victor/unganisha/lib/BootBot.js:647:16)
    at app.post (/home/victor/unganisha/lib/BootBot.js:634:12)
    at Layer.handle [as handle_request] (/home/victor/unganisha/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/victor/unganisha/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/victor/unganisha/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/victor/unganisha/node_modules/express/lib/router/layer.js:95:5)
    at /home/victor/unganisha/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/victor/unganisha/node_modules/express/lib/router/index.js:335:12)

**Comment by HellCatVN** [comment]
please searching before asking . Your solution is written at issue #86

**Comment by iamvictorabedi** [comment]
Fixed it long time ago. Sorry I didn't close the issue
